version: '3'
services:

  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    networks:
      - base
    volumes:
      - ssl_certs:/var/lib/https-portal
    env_file:
      - https.env
    # environment:
    #   DOMAINS: 'myui.com -> http://ui:8200, muconsul.com -> http://consul:8500'
    #   STAGE: 'production'
    #   FORCE_RENEW: 'true'

  consul:
    image: "consul"
    networks:
      - base
    hostname: "consul"
    command: "agent -dev -client 0.0.0.0"
    ports:
      - "8400"
      - "8500"
      - "8600:53/udp"

  vault:
    depends_on:
      - consul
    image: "vault"
    networks:
      - base
    hostname: "vault"
    environment:
      VAULT_ADDR: http://127.0.0.1:8200
    ports:
      - "8200"
    volumes:
      - ./tools/wait-for-it.sh:/wait-for-it.sh:z
      - ./config/vault:/config:z
      - ./config/vault/policies:/policies:z
    entrypoint: /wait-for-it.sh -t 20 -h consul -p 8500 -s -- vault server -config=/config/with-consul.hcl

  ui:
    image: djenriquez/vault-ui
    networks:
      - base
    depends_on:
        - vault
        - consul
    ports:
      - "8000"
    env_file:
      - ui.env
    # environment:
    #   VAULT_URL_DEFAULT: https://myui.com
    #   VAULT_AUTH_DEFAULT: GITHUB


networks:
  base:

volumes:
  ssl_certs: